version: "3.8"
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"   # MQTT TCP
      - "9001:9001"   # MQTT Websockets
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./config/passwd:/mosquitto/config/passwd
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    restart: unless-stopped
